### ISSUE TITLE
Doesn't show up in plugin catalog

### ISSUE THREAD

**Issue by joldeski** [9p4/jellyfin-plugin-sso#3]
After adding the repository URL, the plugin doesn't display in the plugin catalog.
I'm running the current stable version of Jellyfin, version 10.7.7, and your repo advertises that the target version is 10.8.0.0, so I'm assuming that's why the plugin isn't displayed.
Does the plugin require any 10.8 specific features that aren't available on the current stable? I've just manually installed it by dragging it to the /var/lib/jellyfin/plugins dir, pending setup with my keycloak install.

Btw- thanks for developing this!

**Comment by 9p4** [comment]
This plugin is built with .NET 6. Jellyfin 10.7.7 is using .NET 5, and 10.8 is using .NET 6. If the plugin runs, you may run into some issues with the difference in runtimes and whatnot. Since JF 10.8 is nearly at release, I don't want to work to port this plugin (which is still in alpha) to an older release.

No problem! I've been working on adding SSO to a lot of programs recently.
