### ISSUE TITLE
Remove SAML Support

### ISSUE THREAD

**Issue by 9p4** [9p4/jellyfin-plugin-sso#42]
It seems like nobody is using SAML, and removing it would greatly improve the maintainability of the codebase. No need for a second admin panel, small configuration, easier maintainability.

Any thoughts? Is anyone using SAML?

**Comment by DefectX11** [comment]
Now knowing this plugin exists, I'll be almost certainly using it. I'd be happy to provide feedback as needed. 

Frankly I'm not sure why more aren't using SAML or interested in it. It's a great, flexible protocol that's being used more and more frequently. Perhaps it is a bit of a "chicken and the egg" situation. SAML really shines when all your applications support it, otherwise there's not really much of a "single" sign on aspect to it. Since nobody else has it, nobody bothers to add it in as an option.

**Comment by 9p4** [comment]
Why do you use SAML over OpenID? Just curious ;)

**Comment by DefectX11** [comment]
Only because it's a protocol I have lots of experience with from work, and I have enterprise grade systems that all tie in via SAML. So, nice to leverage that infrastructure for personal services as well.
