### ISSUE TITLE
GUI to login

### ISSUE THREAD

**Issue by helmut72** [9p4/jellyfin-plugin-sso#57]
You wrote: `Limitations - There is no GUI to sign in.`

Is this a limitation of Jellyfin Plugins or not? If not, I ask for a login GUI. Thanks.

**Comment by Cookie-Monster-Coder** [comment]
There is no reason to have a GUI, I'm pretty sure. You would use your sso authentication app as the GUI for the login.

**Comment by helmut72** [comment]
I mean the button "login with Authelia" next to the common username/password field like in apps with oidc.

**Comment by 9p4** [comment]
See https://github.com/9p4/jellyfin-plugin-sso/issues/16#issuecomment-1126016947

**Comment by helmut72** [comment]
Give it another try...

> There is no reason to have a GUI, I'm pretty sure.

How to login to Jellyfin with OIDC if there is no button to use OIDC login? Even if I login to Authelia from other Apps (Gitea, Portainer...) or even on the Login page from Authelia, there is still a login page when opening Jellyfin. This is what I asked for, when I ask for a Login GUI.

> See [#16 (comment)](https://github.com/9p4/jellyfin-plugin-sso/issues/16#issuecomment-1126016947)

This looks like a discussion, but doesn't explain how to setup or enable Jellyfin to use OIDC after SSO Plugin is configured from this manual:
https://github.com/9p4/jellyfin-plugin-sso/blob/main/providers.md

Something which need to setup in Jellyfin? Using latest Jellyfin and SSO plugin from today.

**Comment by 9p4** [comment]
From the documentation:

> There is no GUI to sign in. You have to make it yourself! The buttons should redirect to something like this: https://myjellyfin.example.com/sso/SAML/p/clientid replacing clientid with the provider client ID and SAML with the auth scheme (either SAML or OID).

**Comment by depuits** [comment]
It was not directly clear for me either, but after thoroughly reading #16 I've worked it out.

What you want to do is go to the admin dashboard and there the `General` section. And scroll down to `Branding`.

There you need to fill in `Logo disclaimer` and `Custom CSS code` as the screenshot below. I'm using **authentik** so that is what is used in the example.

![image](https://user-images.githubusercontent.com/3755674/194753702-c33a8759-d6c1-4486-9b83-b02976fec947.png)

Below the `Logo disclaimer`. You need to change the url in `href` by changing the url to your server and potentially the end to what the provider name is used in the plugin settings.

```
<a href="https://myjellyfin.example.com/sso/OID/p/authentik" class="raised cancel block emby-button authentik-sso">
Sign in with Authentik&nbsp;
<img alt="OpenID Connect (authentik)" title="OpenID Connect (authentik)" class="oauth-login-image" src="https://raw.githubusercontent.com/goauthentik/authentik/master/web/icons/icon.png">
</a>
```

and `Custom CSS code`

```
/* Hide this in lieu of authentik link */
.emby-button.block.btnForgotPassword {
   display: none;
}

/* Make links look like buttons */
a.raised.emby-button { 
   padding: 0.9em 1em;
   color: inherit !important;
}

/* Let disclaimer take full width */
.disclaimerContainer {
   display: block;
}

/* Optionally, apply some styling to the `.authentik-sso` class, probably let users configure this */
.authentik-sso {
   /* idk set a background image or something lol */
}

.oauth-login-image {
    height: 24px;
    position: absolute;
    top: 12px;
}
```

This results in following view to login
![image](https://user-images.githubusercontent.com/3755674/194753828-6a8c820d-a2f4-46b6-b598-70e6d91e9e93.png)

Only "problem" is that the login opens in a new tab.

**Comment by helmut72** [comment]
Thanks! This is what I've asked for.
